services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapimongo_app
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    command: poetry run uvicorn users_crm.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ".env"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ".env"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ".env"

volumes:
  mongo_data:
